config/routes.rb
Rails.application.routes.draw do
root 'schools#index'

resources :schools

end

app/models/school.rb
class School < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :school, only: [:show, :edit, :update, :destroy]
  def index
    @schools = School.all 
  end

  def show
  end

  def edit
  end

  def update
    if @school.update(school_params)
      redirect_to school_path(@school)
    else
      render :edit
    end
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to school_path(@school)
    else
      render :new
    end
  end

  def destroy
    @school.destroy
    redirect_to schools_path
  end

  private
    def school_params
      params.require(:school).permit(:name, :year_built, :phone_number, :address, :email)
    end

    def school
      @school = School.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Schools</a>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Add School', new_school_path %></li>
        </ul>
    </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolRspec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='school-form col-sm-10 col-sm-offset-1 text-center'>
      <%= form_for @school do |f|%>

        <br />
          <%= f.label :name %>
        <div class='form-group row'>
          <%= f.text_field :name %>
        </div>

          <%= f.label :phone_number %>
        <div class='form-group row'>
          <%= f.text_field :phone_number %>
        </div>

          <%= f.label :address %>
        <div class='form-grou row'>
          <%= f.text_area :address %>
        </div>

          <%= f.label :email %>
        <div class='form-group row'>
          <%= f.text_field :email %>
        </div>

          <%= f.label :year_built %>
        <div class='form-group row'>
          <%= f.text_field :year_built %>
        </div>

        <br />
        
        <%= f.submit 'Save', :class => 'btn btn-secondary school-save-btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/schools/edit.html.erb
<h1 class='text-center'>Edit: <%= @school.name %></h1>
<%= render 'form' %>

app/views/schools/index.html.erb
  <div class='text-center'>
    <h3>School List</h3>
  </div>

<div class='container'>
  <div class='row'>
    <div class='card-container'>
      <% if ! @schools.empty? %>
        <% @schools.each do |school| %>
          <div class='index-card text-center col-sm-4'>
            <div class='school-name-card'>
              <h4><%= school.name %></h4>
            </div>
            <hr />
            <%= link_to 'Visit School', school_path(school), class: 'visit-school-link' %>
            <img class='default-school-img-index' src='http://quickwit3d.com/wp-content/uploads/2013/05/BnaiYoelSchool_Exterior.jpg' />
          </div>
        <% end %>
      <% else %>
        <div class='text-center'>
          <h4>No Schools Found. You should make one.</h4>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/schools/new.html.erb
<h3 class='text-center'>Add School</h3>
<%= render 'form' %>

app/views/schools/show.html.erb
<div class='row'>
  <div class='col-sm-6 col-sm-offset-3 text-center'>
    <h3><%= @school.name %></h3>
  </div>
</div>

<div class='row'>
  <div class='col-sm-6 show-info-div'>
    <h6><%= @school.phone_number %></h6>
    <h6><%= @school.address %></h6>
    <h6><%= @school.email %></h6>
    <h6><%= @school.year_built %></h6>
  </div>

  <div class='col-sm-6 col-sm-offset-3 text-center show-img-div'>
    <img class='default-school-img' src='http://quickwit3d.com/wp-content/uploads/2013/05/BnaiYoelSchool_Exterior.jpg' />
  </div>
</div>


<div class='row'>
  <div class='col-sm-2'>
    <%= link_to 'Edit', edit_school_path(@school), class: 'btn btn-warning edit-btn' %>
  </div>
</div>